upgrade keycloak
Informasjonsforvaltning/sso pull request #112
Opened 2022-09-05 08:27 UTC by NilsOveTen

2022-09-05 08:30 UTC, tenstad approved these changes

2022-09-06 06:30 UTC, tenstad submitted a review, later dismissed

2022-09-16 10:33 UTC, valosnah requested changes
Da har vi testet nok til å kunne oppdatere til app_name: sso ?

2022-09-22 12:53 UTC, stigbd approved these changes

2022-09-22 18:27 UTC, pooriamehregan approved these changes

2022-09-23 05:40 UTC, merged